name: Update Model Index Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    generate-indexes:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Generate index.html for each model folder
              run: |
                  for dir in models/*/; do
                    [ -d "$dir" ] || continue
                    index_file="${dir}index.html"
                    echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Index of ${dir}</title></head><body>" > "$index_file"
                    echo "<h1>Index of /${dir}</h1><ul>" >> "$index_file"

                    for file in "$dir"*; do
                      fname=$(basename "$file")
                      if [ "$fname" != "index.html" ]; then
                        echo "<li><a href=\"$fname\">$fname</a></li>" >> "$index_file"
                      fi
                    done

                    echo "</ul></body></html>" >> "$index_file"
                  done

                  # Generate models/index.html to list all model folders
                  models_index="models/index.html"
                  echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Index of models/</title></head><body>" > "$models_index"
                  echo "<h1>Index of /models/</h1><ul>" >> "$models_index"

                  for dir in models/*/; do
                    [ -d "$dir" ] || continue
                    dname=$(basename "$dir")
                    echo "<li><a href=\"$dname/\">$dname/</a></li>" >> "$models_index"
                  done

                  echo "</ul></body></html>" >> "$models_index"

            - name: Commit and push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add models/index.html
                  git add models/*/index.html

                  if git diff --cached --quiet; then
                    echo "No changes to commit."
                  else
                    git commit -m "Update model index.html files"
                    git push
                  fi
