name: Update Model Index Pages

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    generate-indexes:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Generate index.html for each model folder
              run: |
                  # MIME types / extensions to match as image files
                  IMAGE_EXTENSIONS="jpg jpeg png webp gif bmp svg tiff"

                  # Generate index.html and metadata.json inside each model folder
                  for dir in models/*/; do
                    [ -d "$dir" ] || continue

                    # index.html
                    index_file="${dir}index.html"
                    echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Index of ${dir}</title></head><body>" > "$index_file"
                    echo "<h1>Index of /${dir}</h1><ul>" >> "$index_file"

                    for file in "$dir"*; do
                      fname=$(basename "$file")
                      if [ "$fname" != "index.html" ]; then
                        echo "<li><a href=\"$fname\">$fname</a></li>" >> "$index_file"
                      fi
                    done

                    echo "</ul></body></html>" >> "$index_file"

                    # metadata.json
                    metadata_file="${dir}metadata.json"
                    echo '{' > "$metadata_file"
                    echo '  "images": [' >> "$metadata_file"

                    first=true
                    for ext in $IMAGE_EXTENSIONS; do
                      for img in "$dir"*.$ext; do
                        [ -f "$img" ] || continue
                        fname=$(basename "$img")
                        if [ "$first" = true ]; then
                          echo "    \"$fname\"" >> "$metadata_file"
                          first=false
                        else
                          echo "    ,\"$fname\"" >> "$metadata_file"
                        fi
                      done
                    done

                    echo '  ]' >> "$metadata_file"
                    echo '}' >> "$metadata_file"
                  done

                  # Generate models/index.html to list all model folders
                  models_index="models/index.html"
                  echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>Index of models/</title></head><body>" > "$models_index"
                  echo "<h1>Index of /models/</h1><ul>" >> "$models_index"

                  for dir in models/*/; do
                    [ -d "$dir" ] || continue
                    dname=$(basename "$dir")
                    echo "<li><a href=\"$dname/\">$dname/</a></li>" >> "$models_index"
                  done

                  echo "</ul></body></html>" >> "$models_index"
            - name: Commit and push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add models/index.html
                  git add models/*/index.html

                  if git diff --cached --quiet; then
                    echo "No changes to commit."
                  else
                    git commit -m "Update model index.html files"
                    git push
                  fi
